name: "RealQuestions"
description: "RealQuestions Australia"

url: "http://localhost:4000"
#baseurl: "https://realquestions.net.au"

# paginate: 10
# gems: [jekyll-paginate]
# paginate_path: "page:num"

markdown: kramdown
permalink: pretty
highlighter: pygments.rb
